# Generated by Django 5.1.15 on 2026-03-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeingrediente', models.CharField(max_length=128)),
                ('tipo_unidade', models.CharField(choices=[('G', 'Gramas'), ('ML', 'Mililítros'), ('UN', 'unidades')], max_length=2)),
                ('observacoes', models.TextField(blank=True)),
                ('unidade_usada', models.IntegerField(default=1)),
                ('calorias_unidade', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomereceita', models.CharField(max_length=128)),
                ('modo_de_preparo', models.TextField(blank=True)),
                ('ingredientes', models.ManyToManyField(to='receitas.ingredientes')),
            ],
        ),
    ]
