# Generated by Django 5.1.15 on 2026-03-13 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredientes',
            new_name='Ingrediente',
        ),
        migrations.RenameModel(
            old_name='Receitas',
            new_name='Receita',
        ),
    ]
