# Generated by Django 5.1.15 on 2026-04-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_ingrediente_created_date_ingrediente_published_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='ingrediente_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='receita',
            name='receita_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
