# Generated by Django 5.1.15 on 2026-04-09 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_ingrediente_ingrediente_imagem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='nomereceita',
            new_name='nome_da_receita',
        ),
    ]
